# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  webSourcesDirectory: '$(Build.SourcesDirectory)\src\DZarsky.TS3Viewer2.Web'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.x'

- task: NuGetToolInstaller@1

- task: NodeTool@0
  inputs:
    versionSpec: '18.x'

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '$(solution)'
    feedsToUse: 'select'
    vstsFeed: 'fec35eb5-47a4-4789-9fd4-a3bcd21af267/a213a184-fce7-4021-9560-8d466b7c6eba'

- task: MSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArchitecture: 'x64'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    msbuildArguments: '/p:DeployOnBuild=True'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: '$(webSourcesDirectory)'

- task: EnvTransform@0
  inputs:
    inputType: 'inline'
    content: |
      API_BASE_URL=$(api-baseurl-test)
    outputFile: '.env.test'

- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: '$(webSourcesDirectory)'
    customCommand: 'run build:test'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(webSourcesDirectory)\build'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)\DZarsky.TS3Viewer2.Web\test'

- task: EnvTransform@0
  inputs:
    inputType: 'inline'
    content: |
      API_BASE_URL=$(api-baseurl-prod)
    outputFile: '.env.production'

- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: '$(webSourcesDirectory)'
    customCommand: 'run build:prod'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(webSourcesDirectory)\build'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)\DZarsky.TS3Viewer2.Web\prod'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
