services:
  teamspeak:
    image: ertagh/teamspeak3-server:latest-box-predownloaded
    ports:
      - "9987:9987/udp"
      - "10011:10011"
      - "30033:30033"
    environment:
      TS3SERVER_LICENSE: accept
    volumes:
      - ts3data:/var/ts3server
      - ./query_ip_allowlist.txt:/var/ts3server/query_ip_allowlist.txt
    networks:
      - ts3network

  api:
    build:
      context: src/
      dockerfile: DZarsky.TS3Viewer2.Api/Dockerfile
    ports:
      - "20800:8080"
    depends_on:
      - teamspeak
    environment:
      TeamSpeakServer__Host: teamspeak
      TeamSpeakServer__Port: "10011"
      TeamSpeakServer__Login: "${TS3_QUERY_LOGIN}"
      TeamSpeakServer__Token: "${TS3_QUERY_TOKEN}"
      Security__Jwt__Issuer: "ts3viewer2-dev"
      Security__Jwt__Key: "${SECURITY_JWT_KEY}"
      Security__Jwt__Audience__0: "ts3viewer2-dev"
      RUN_MIGRATIONS: "true"
      ConnectionStrings__db: "Data Source=/app/data/ts3viewer2.db"
      Security__AllowedOrigins__0: "http://localhost:20801"
    volumes:
      - ./src/DZarsky.TS3Viewer2.Api/appsettings.json:/app/appsettings.json:ro
      - apidata:/app/data
    networks:
      - ts3network

  web:
    build:
      context: src/DZarsky.TS3Viewer2.Web/
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: development
    ports:
      - "20801:80"
    depends_on:
      - api
    networks:
      - ts3network

networks:
  ts3network:

volumes:
  ts3data:
  apidata:
