services:
  teamspeak:
    image: ertagh/teamspeak3-server:latest-box-predownloaded
    ports:
      - "9987:9987/udp"
      - "10011:10011"
      - "30033:30033"
    environment:
      TS3SERVER_LICENSE: accept
    volumes:
      - ts3data:/var/ts3server
      - ./query_ip_allowlist.txt:/var/ts3server/query_ip_allowlist.txt
    networks:
      - ts3network

  api:
    build:
      context: src/
      dockerfile: DZarsky.TS3Viewer2.Api/Dockerfile
    ports:
      - "20800:8080"
    depends_on:
      - teamspeak
    environment:
      TeamSpeakServer__Host: teamspeak
      TeamSpeakServer__Port: "10011"
      TeamSpeakServer__Login: "serveradmin"
      TeamSpeakServer__Token: "8MGsqb8c"
      Security__Jwt__Issuer: "ts3viewer2-dev"
      Security__Jwt__Key: "eyJrdHkiOiJSU0EiLCJuIjoidGI2LXVPd29YWXc2LUh3NUViZUZhLWZrTFVYXzR2UjN3dFZvZnFDbmtCZ0lrMnBrdDRnT09ZSXYzMkNpWU9SWTltN3FIUl9RVWcxTWpKdWFybURTVk1yTXZYOWl0dTA4WlczZTVIUHkxTkpXeVB2akRYUWZmeHpEc1piYlh3akY5SWdDQkVlZkZndFlZQnQ4eGZ1WUxOVzlVRnQzZjM5MUcyNXdsc1VRVVBhOGpWSTZBRlRieERJRV82Ym5hUDk0bGxiNlhraUYxUW9sRmxpYnBEbFZoQlBGUmhUaS1FMGk5Ri11NDF5TlQzVFFhM1o2UE5CY0d4enRFUDhySTNtYnZwb2NhckpZZWFmM2Z4dmNYYkQyZFFkQVBlMEFkWmlJWDcwRE1ZS1c2NVRtVFFkdEdMTm4yMWxTOFVucFcxSXBYcTR6QnluSVZMcmNIM0pxTjk4dkxRIiwiZSI6IkFRQUIiLCJkIjoiSGVGVUhIV1JKbDRyaE5aeGtJamVhZkQ0V2Z3bjk1R1BUZ3hGajRvTXVudEZENjEtalJFVW01NWNqZ3BtYi0waTlqTWlrUEs5em51cXdmUkVRRmFoUmZrSW84QVpnLThwanBoN2ZJNVdsbWhWaGRvcHlIaTJ3X0JfLVFiUEhzY0R1cklRdU5Eb3BoaHI2WE1qZHE1b1pMaW9WUm1Rb2pqYmtVeTlQSUItTF8wMWY4di1VM25LYUUxWDRJQjBnMVFGY3NNU2M4eHByZW16bkFqNWR4T291amplODR1SXluVTdNbERLdWhYSmlvNG1mYXBZN2J4UjFPc3Q2U2dubFBYNDNvRVVBY05EejNINlF6bGFGTG9FMDBEZk9aMkdTelU5d2NSbjZjc0dCbGViZlZrNWZfWms1bmpJMUtwb3A3dUxaYVdKSF9ibXdTRTJqemRLX285aGdRIiwicCI6IjhVc1BLNjlDUkh6WVhoSWJBVG1GWGlYdnhtWEhDcDlncjhXMDJwV2xZWWo0S1hFbTRTeFpsVlh0YXBMSTcyRHNRbm1fRGxwZC1iYUdzTzBDMm0xOFV4cDRFb2N2NkR5VEl2blNKUllKeVVDYjFYQ0pvRW5ZcGRjMFFKeHlvTHlKRmNKbVFoYy1MaHN1dnVBalZwNGxjaHhUcVJSc2haR3RmRnpiU3F0RTlZRSIsInEiOiJ3TktMemNnR3g0Z1Rpa294bUlpU3h0Rk9CT0NFb1VJZFYtNWFBV0pIWWJLdjg1Q1dLVHk2NXNyUG84TzROWWdMRjdkelpYM0k2MzF4MklLUjA1cVRiQ2xxN1FIV2N3eVFaeTBBZFh1VGxmb0NQRW0xWHZvM2RFUTE2MDZOWmFLN2xXZmg2LWNSNFNsWm50WkprYU1CU3ZFeGs5QnhNOFRqYnpxa3RXSnV4NjAiLCJkcCI6IlE4Tmxsa29ZM1MwR2dweXBFdFg1bTNBaF8yQ3oza3JXRjJiNW5HMXNUWkR1eUl5cmM0OUY5VWQxYm5tY2pvVjB0RktHa2x4VWlmMTFwQmhidGNZTHBUY0l3NE5Oc19YWENIcUtScm9DczQ4LWRGbXZmT0ZnUTJyRmxPT2EyWU01S0hBNDBaU19kS2xUbm0xSjMxaDRnYXhzM2s0TEVCUFNXZHVtQmpsRkc0RSIsImRxIjoiZ05PcXlEX2VGNjJZc0lwRmZJMnkwdGJBYzQyMXp5LW1fenFtTThwX3VveHg5aDhoMUVkWThCMk1nUE9ndlZNNVpnMFJNanZKNDF3YWxmY1dpdlA1andoVkFpaDZLTC02TXRUa081bm16d3NNTjA5ZnVDY2dxYk53LXRldXJMci03U0ZNMWhtNTNsLU1HdzA4ZGVzY1RfLTVpZkozejRpNkUzUncyeWI2c0xrIiwicWkiOiJMTHRiRlN5UXRZYnNpTDZtcHFsU2RjRzNRWTBlZ2hjS3lpelVkV1VWSElyRE9KQ2hlVUozSnphSERjczI5NEtSUUNjRmNOTnltQVRkRVZTdDkzOEoyaERIWjJjMndrd3pSZkhJZmI4dS1PUUNhRmljOGdlT1hReFE5TWRiaTNQNjVLMi1VSlNndHRTOFhHV2t5ZjlNTUFZbEFlSjNZekhualhoZjlyekhVVE0iLCJhbGciOiJSUzI1NiIsInVzZSI6InNpZyJ9"
      Security__Jwt__Audience__0: "ts3viewer2-dev"
      RUN_MIGRATIONS: "true"
      ConnectionStrings__db: "Data Source=/app/data/ts3viewer2.db"
      Security__AllowedOrigins__0: "http://localhost:20801"
    volumes:
      - ./src/DZarsky.TS3Viewer2.Api/appsettings.json:/app/appsettings.json:ro
      - apidata:/app/data
    networks:
      - ts3network

  web:
    build:
      context: src/DZarsky.TS3Viewer2.Web/
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: development
    ports:
      - "20801:80"
    depends_on:
      - api
    networks:
      - ts3network

networks:
  ts3network:

volumes:
  ts3data:
  apidata:
